In [4]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sea
print(np.__version__)
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3)
print(arr3.ndim)
arr4 = np.array([1,2,3,4],ndmin=2)

2.2.5
[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [3]:
!git clone git@github.com:doersaujan/numpy_5_9.git

Cloning into 'numpy_5_9'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


In [11]:
print(arr[2]+arr[3])

7
